parent: classic
name: pstheme
display_name: PS Theme
version: 1.0.0
author:
  name: "KaisarCode"
  email: "kaisar@kaisarcode.com"
  url: "https://kaisarcode.com"

meta:
  compatibility:
    from: 8.0.0
    to: ~
  available_layouts:
    - layout-full-width

global_settings:
  configuration:
    PS_IMAGE_QUALITY: png
  image_types:
    category_default:
      width: 141
      height: 180
      scope: [categories]
    small_default:
      width: 98
      height: 98
      scope: [products]
    medium_default:
      width: 452
      height: 452
      scope: [products]
    home_default:
      width: 250
      height: 250
      scope: [products]
    large_default:
      width: 800
      height: 800
      scope: [products]
    cart_default:
      width: 125
      height: 125
      scope: [products]
  modules:
    to_enable:
      - ps_shoppingcart
      - ps_customersignin
  hooks:
    modules_to_hook:
      displayNav2:
        - ps_customersignin
      displayTop:
        - ps_shoppingcart

assets:
  css:
    - id_name: theme-main
      path: assets/css/theme.css
      media: all
      priority: 50
  js:
    - id_name: theme-main
      path: assets/js/theme.js
      position: bottom
      priority: 50

theme_settings:
  default_layout: layout-full-width
  layouts:
    category: layout-full-width
    product: layout-full-width
    contact: layout-full-width