parent: classic
name: pstheme
display_name: PS Theme
version: 1.0.0
author:
  name: "KaisarCode"
  email: "kaisar@kaisarcode.com"
  url: "https://kaisarcode.com"

meta:
  compatibility:
    from: 8.0.0
    to: ~

global_settings:
  configuration:
    PS_IMAGE_QUALITY: png
  modules:
    to_enable:
      - ps_shoppingcart
      - ps_customersignin
  hooks:
    modules_to_hook:
      displayNav2:
        - ps_customersignin
      displayTop:
        - ps_shoppingcart

assets:
  css:
    - id_name: theme-main
      path: assets/css/theme.css
      media: all
      priority: 50
  js: []

theme_settings:
  default_layout: layout-full-width
  layouts:
    category: layout-full-width
    product: layout-full-width
    contact: layout-full-width